### ISSUE TITLE
System 5.0 and 5.1 freeze the MacvMac-II.js shortly after boot sequence starts

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#300] opened 2024-03-10 13:20 UTC
As seen on here: https://infinitemac.org/1987/System%205.0?infinite_hd=false&saved_hd=false&machine=Mac+II

**Comment by mihaip** [comment] 2024-03-10 16:57
Duplicate of #165 -- I believe this is a limitation of Mini vMac itself.

**Closed by mihaip** 2024-03-10 16:57 UTC

**Comment by that-ben** [comment] 2024-03-10 17:36
Whoops, I missed that thread.  Thanks.
