### ISSUE TITLE
please fix!

### ISSUE THREAD

**Issue by thexboxgod360** [mihaip/infinite-mac#224] opened 2023-09-11 15:39 UTC
#
![Screenshot 2023-09-11 8 37 55 AM](https://github.com/mihaip/infinite-mac/assets/143741867/4659ad32-81b0-4417-89fa-71fc7a4d1c77)

**Comment by mihaip** [comment] 2023-09-11 15:47
Duplicate of #220 (which you also filed). Infinite Mac is a hobby project, there are no expectations for when/if issues are addressed.

In this case you should be able to download and install your own copy of Acrobat Reader too.

**Closed by mihaip** 2023-09-11 15:47 UTC
