### ISSUE TITLE
making qemu-ppc and qemu-x86 for infinite mac (suggestion)

### ISSUE THREAD

**Issue by Pierrestro** [mihaip/infinite-mac#296] opened 2024-02-26 09:58 UTC
qemu is a x86,arm,ppc emulator for our pc and macs but it's slow on certain computers, making qemu-ppc and qemu-x86 for infinite mac will bring rhapbody os and os x it will be a little for some people but will be great, i love the idea of this project but again making qemu-ppc and qemu-x86 for infinite mac will make it better✌️✌️✌️💖💖💖

**Comment by mihaip** [comment] 2024-02-26 15:06
Duplicate of #72 

QEMU would be great, but it's a complex codebase. You can subscribe to the above issue to get updates for when/if it happens.

**Closed by mihaip** 2024-02-26 15:06 UTC
