### ISSUE TITLE
System 7.0: DiskCopy requires 7.0.1

### ISSUE THREAD

**Issue by voltagex** [mihaip/infinite-mac#340] opened 2024-09-21 03:43 UTC
![{14EC8244-A5CB-4B4E-AA1C-71B0BF2BD642}](https://github.com/user-attachments/assets/c5053f75-669e-467b-889d-b4f13d420012)

**Comment by that-ben** [comment] 2024-09-21 13:32
Can you please explain what the issue is? You want to use Disk Copy? Then use it with System 7.0.1 or above, e.g. with 7.1: https://infinitemac.org/1992/System%207.1?machine=Mac+IIfx

**Comment by voltagex** [comment] 2024-09-21 16:30
Sorry, I didn't realise the drives / installed applications were common across different emulated systems.

Thanks, that makes sense.

**Comment by mihaip** [comment] 2024-09-21 18:18
Is there a version of Disk Copy that runs on System 7.0? I tried Disk Copy 4.2 and gives this error message:
![Screenshot 2024-09-21 at 11 17 36@2x](https://github.com/user-attachments/assets/588655b0-491a-4462-a82c-69ff5d121657)

**Comment by that-ben** [comment] 2024-09-21 18:18
Disk Copy 4.2 runs under System 6 so it has got to work under 7.0 but maybe it doesn't like your ROM?

**Comment by mihaip** [comment] 2024-09-21 18:41
This was with Basilisk II and the IIfx ROM (the default config on infinitemac.org). Will look into adding 4.2 as an option in the Infinite HD.

**Comment by that-ben** [comment] 2024-09-21 18:44
Nope, it will not run under System 7.0.0 from a 68020 architecture.  BTW if you guys want to test anything easily, I've made a regular disk image that you can drag and drop onto Infinite Mac with all aforementioned versions of Disk Copy (4.2, 5.0 and 5.5) : https://www.macintoshrepository.org/files/direct/Disk_Copy_4-5.dsk

**Comment by mihaip** [comment] 2024-11-10 23:52
Actually, since 4.2 doesn't work under Basilisk II (as far as I can tell), I won't be adding, since it'll likely generate confusion.

**Closed by mihaip** 2024-11-10 23:52 UTC
