### ISSUE TITLE
TCP to the outside world supposed to be supported?

### ISSUE THREAD

**Issue by onpaws** [mihaip/infinite-mac#107] opened 2023-02-20 20:22 UTC
This project is amazing, great work!
I particularly appreciate the drag and drop to upload feature, very intuitive and a nice touch.

### TL,DR
When using https://macos9.app, are apps that open raw TCP sockets to the outside world (e.g. Netscape) supposed to work?

### Back story
I recently learned that the SSA offers a tool called [anypia](https://www.ssa.gov/oact/anypia/), [source](https://www.ssa.gov/oact/anypia/source.html) and I got curious to try it out. (`anypiamacprojOSX/read me.txt` included below)
Because the Mac app is vintage and doesn't work on modern macOS°, I thought I'd see if I could compile + run it using https://macos9.app. 

I got as far as dragging in the source files (.sitx), and opening Netscape, but then I remembered browsers (to my knowledge) don't support opening raw sockets from JS/frontend code. So this error seems like it should be unsurprising:

<img src="https://user-images.githubusercontent.com/182515/220186992-0462a700-c437-460f-8faa-f8831a736633.png" width="500" />

I noticed TCP/IP control panel shows `169.254.x.x` addresses (I guess it matches [3927](https://www.ietf.org/rfc/rfc3927.txt) i.e. what happens when no DHCP server response.)
<img src="https://user-images.githubusercontent.com/182515/220190311-0d3daca8-3565-4455-8e2a-79ab57a4e9b1.png" width="500" />

So I was surprised by [this](https://github.com/mihaip/infinite-mac/issues/45#issuecomment-1100209994) comment which seems to suggest TCP may actually work, but doesn't mention actually opening sockets. _Should apps Hotline/Netscape/etc be able to make outgoing TCP connections?_

Thank you again for your great work, been a fun trip down nostalgia lane :)

<details>

<summary>read me.txt</summary>

```
// Read Me.txt

This is a straight conversion to OS X (and OS 9) of the social security benefit
calculator at http://www.ssa.gov/OACT/ANYPIA/source.html

There is no warranty. Use at your own risk.

This compiles with Metrowerks Codewarrior 9.3.

To compile it, you'll need to download oactobjs.sea from 
http://www.ssa.gov/OACT/ANYPIA/source.html, unpack it, and put the resulting 
oactobjs folder next to the anypiamacprojOSX folder (the folder that contains this file).

My work on this program is hereby placed in the public domain.

David Phillip Oster April 25, 2005

```

</details>

° I'm on Ventura 13.2.1/Intel

**Comment by onpaws** [comment] 2023-02-21 00:49
TIL that another [project](https://github.com/codeforboston/windfall-elimination) appears to have already WASMified the C I was looking to compile in Mac OS 9. So I'm intending to go that direction to avoid having to mess with proprietary old 90s compilers 😅 

Still I remain curious about the "TCP to the outside world" question, AIUI historically it's been disallowed for security reasons, but it looks like in more recent days [new](https://github.com/GoogleChromeLabs/telnet-client) [things](https://github.com/WICG/direct-sockets/issues/46#issuecomment-1436664185) are [happening](https://chromestatus.com/feature/6398297361088512). Maybe this situation will improve 🤞

**Comment by mihaip** [comment] 2023-02-21 01:51
TCP is not currently supported. What I did add was AppleTalk support so that you could have a "LAN" where other emulator instances could see each other (e.g. for multiplayer games). This blog post has more details: https://blog.persistent.info/2022/07/infinite-mac-networking.html

I've left #45 open as a feature request, closing this as a duplicate of it.

**Closed by mihaip** 2023-02-21 01:51 UTC

**Comment by onpaws** [comment] 2023-03-14 04:39
Thank you for the detailed blog post about this. In particular this [commit](https://github.com/mihaip/infinite-mac/commit/e302338a18f63ddc00844aac8de2821696891cf0) I find a really interesting read. Thank you for open sourcing your work on this 🙏
