### ISSUE TITLE
Load from URL... using internet archive ISO in a 7z

### ISSUE THREAD

**Issue by gingerbeardman** [mihaip/infinite-mac#273] opened 2023-12-23 14:15 UTC
"Load from URL..." with the below URL doesn't work

https://archive.org/download/hyperlib-1993-vol7/HYPERLIB-1993-VOL7-CD2.ISO.7z/HYPERLIB-1993-VOL7-CD2.ISO

> Could not load CD-ROM: CD-ROM HEAD request failed: no Content-Length

Should I expect this to work or not?

If not is there any alternative? I uploaded over 300 CD-ROM to IA but they are all 7z with ISO inside (to save my upload time)

**Comment by mihaip** [comment] 2023-12-23 16:36
While archive.org does provide a way to get at individual files within compressed archives, it doesn't allow streaming those files, so they can't be directly used with Infinite Mac.

This is fundamentally the same as needing compressed file support (#204), marking this as a duplicate of that.

**Closed** 2023-12-23 16:37 UTC
