### ISSUE TITLE
Myth: The Fallen Lords, is working, however error popups become common.

### ISSUE THREAD

**Issue by MarathonMasaster** [mihaip/infinite-mac#257] opened 2023-11-21 18:49 UTC
Here are the images of the popups, otherwise the game runs smoothly when they dont happen out of the blue.
One that says: Could Not Load Disk Chunk/CD
Another: Memory Access Out of Bounds (Fully crashes and stops Infinite Mac)
The Other: Aborted() with -sASSERTIONS for more info

Any workarounds to this?

**Comment by mihaip** [comment] 2023-11-27 06:12
Duplicate of #254. The PowerPC emulation is generally known to have issues, it's not specific to this game.

If you're looking to play the game for an extended period of time, you're probably better off setting up a native installation of SheepShaver.

**Closed by mihaip** 2023-11-27 06:12 UTC
