### ISSUE TITLE
Browser download does not trigger for certain files

### ISSUE THREAD

**Issue by Synoptic2** [mihaip/infinite-mac#138] opened 2023-04-03 01:50 UTC
If I create a .DSK file from Dick Copy utility, putting that file into the "Upload" directory does not trigger a download file in my browser.
Tested with FireFox and Crome.

if I put any other file it will work.

**Comment by GFerrara** [comment] 2023-04-05 00:35
I have the same problem (browser download doesn't trigger) putting graphic files (BMP, GIF, JPEG files) into "Upload" folder. This problem sometimes (not very frequently) disappears (I mean the browser download starts) but this is the very exception: normally it doesn't work. I have tested it with both the last version of Firefox and Chrome. This happens both on Windows and Linux.

**Comment by mihaip** [comment] 2023-04-05 05:40
I'm not able to reproduce this, but it may be a timezone issue (I'm in California). What timezones are you all in?

**Comment by mihaip** [comment] 2023-04-05 06:02
I was able to reproduce it by changing my computer's timezone, the issue should be fixed now.

**Closed** 2023-04-05 06:02 UTC

**Comment by GFerrara** [comment] 2023-04-08 21:08
I confirm the problem has been fixed. Anyway... my timezone is CEST. 
Thank you for the fix.

**Comment by parkerlreed** [comment] 2023-04-18 21:47
I can trigger it not offering a download by creating a PNG with GraphicConverter and trying to transfer into Outside World > Uploads. Nothing happens when dragging the file onto the folder.

**Comment by parkerlreed** [comment] 2023-04-18 21:59
Scratch that! Completely missed the download happening in the background. Seems the previous fix was related and it successfully exported. Thanks!
